# Generated by Django 4.2.2 on 2026-02-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название курса")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/preview/course", verbose_name="Превью курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/preview/lesson", verbose_name="Превью урока"
                    ),
                ),
                ("linc", models.CharField(max_length=150, unique=True, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
